language: java

addons:
  sonarcloud:
     organization: "1905-uta-java"
before_install:
  - wget https://ojdbc-project2-avoidance.s3.us-east-2.amazonaws.com/ojdbc7-12.1.0.jar
  - mvn install:install-file -DgroupId=com.oracle -DartifactId=ojdbc7 -Dpackaging=jar -Dversion=12.1.0 -Dfile=ojdbc7-12.1.0.jar -DgeneratePom=true
script:
  - mvn clean verify sonar:sonar -Dsonar.projectKey=1905-uta-java-TruckMaster
